### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by a626677909** [realpython/cookiecutter-flask-skeleton#41]
Profiler not active
The profiler is not activated, activate it to use it

**Comment by mjhea0** [comment]
What do you mean by profiler?

**Comment by a626677909** [comment]
![image](https://user-images.githubusercontent.com/19469719/37663906-3d4aca7a-2c95-11e8-9331-ab519790b2ac.png)
![image](https://user-images.githubusercontent.com/19469719/37663924-476df0b8-2c95-11e8-80b9-e2d2ec1d26ef.png)

**Comment by a626677909** [comment]
These are what I got. I have no idea how to input data.

**Comment by mjhea0** [comment]
https://flask-debugtoolbar.readthedocs.io/en/latest/panels.html#profiler
