### ISSUE TITLE
cookiecutter https://github.com/realpython/cookiecutter-flask-skeleton.git - asks for password?????

### ISSUE THREAD

**Issue by lesatdgl** [realpython/cookiecutter-flask-skeleton#53]
cookiecutter https://github.com/realpython/cookiecutter-flask-skeleton.git - asks for password?????

**Comment by mjhea0** [comment]
It shouldn't ask for a password. Can I see a screenshot of your terminal?

**Comment by lesatdgl** [comment]
I crawled through it and did a re-install and found a known bug ##4618 - I'm guessing that's involved and IAC until that resolved, there's no sense in messing with this
Thanks for your response. I'll close this until...
