### ISSUE TITLE
New click version breaks cli commands

### ISSUE THREAD

**Issue by vadave** [realpython/cookiecutter-flask-skeleton#55]
with version 7.0, the click library developers changed the behavior for cli subcommands containing an underscore such that they are now exposed with a dash in place of the underscore. This means that instead of `python manage.py create_db`, the correct command is `python manage.py create-db`, etc.

When I have a few minutes available I'll submit a PR fixing the documentation to reflect this change.

**Comment by mjhea0** [comment]
Yes, I am slowly updating all my blog posts and code repos, etc. to take this change into account. I should be able to update this repo over the weekend... unless you beat me to it! :)
